version: '3'
services:
    irtex-fronten-dev:
        image: irtex-ui-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "4200:4200"
        volumes:
            - "./:/angular"
            - "irtex_node_vol:/angular/node_modules"
volumes:
  irtex_node_vol: